name: Build everything
on: [push]

jobs:
  build:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: build
        run: cmake --build build
